### ISSUE TITLE
Possibility to use adjust in web application via javascript

### ISSUE THREAD

**Issue by dwadezp** [adjust/sdks#44]
Hello Guys,

we are looking to possibility to use adjust in web application ( single page application ).
Is it possible? Because in this repo i found only related to mobile devices sdks.

Thank you in advance for the answer

**Comment by uerceg** [comment]
Hi @dwadezp 

When it comes to this topic, my advice would be to ping our support team by sending them email with this question to support@adjust.com and they'll provide you with all the answers you need.

Cheers!
